version: "3.7"
services:
    server:
        image: python:3.8
        working_dir: /app
        volumes: 
            - ./server:/app
        command: python3 -m pip install -r requirements.txt; python3 run.py
        environment:
            - GIPHY_API_KEY
        expose: 
            - 5000
