version: "3.7"
services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
    # server:
    #     build: 
    #         context: server
    #         dockerfile: Dockerfile
    #     ports:
    #         - 5000:5000
    #     environment: 
    #         - BASE_URL
    #         - POSTGRES_URL
    #         - POSTGRES_PORT
    #         - POSTGRES_USER
    #         - POSTGRES_PASSWORD
    #         - POSTGRES_DB
    #         - SECRET_KEY
    # client:
    #     build: 
    #         context: client
    #         dockerfile: Dockerfile
    #     ports:
    #         - 8080:8080
    #     environment: 
    #         - VUE_APP_BASE_URL
