version: "3.7"
services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB

    api:
        build:
            context: server
            dockerfile: Dockerfile
        container_name: api
        environment: 
            - BASE_URL
            - POSTGRES_URL
            - POSTGRES_PORT
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - SECRET_KEY
        restart: always
        volumes:
            - ./server/:/app
        expose:
            - 9000

    ui:
        build:
            context: client
            dockerfile: Dockerfile
        container_name: ui
        restart: always
        expose:
            - 80

    nginx:
        build: 
            context: nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        ports:
            - "8000:8000"
            - "8001:80"